### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Computarfant** [martinstereo/nosted-mvc#125]
Må skrive dokumentasjon til metoder.

**Comment by martinstereo** [comment]
• Applikasjonens oppsett (arkitektur)
• Hvordan applikasjonen kjøres (kjøring på Docker, kobling mot database, osv)
• Komponenter av applikasjonen (MVC, repo, klasser, osv)
• Funksjonaliteter i applikasjonen (det som applikasjonen gjør)
• Logikken av applikasjonen (koden)
• Unit testing scenarier type tester f. eks. UI test (test kode/skripter og resultater)
• Hvordan applikasjonen brukes (brukesanvisning)
• Endringer i koden (hva er det som ble endret, av hvem og når)

Hvem dokumenterer du for?
Målgrupper:
• Andre utviklere hos en klient som Nøsted
• Applikasjonens oppsett (arkitektur)
• Hvordan applikasjonen kjøres (kjøring på Docker, kobling mot database, osv)
• Komponenter av applikasjonen (MVC, repo, klasser, osv)
• Funksjonaliteter i applikasjonen (det som applikasjonen gjør)
• Logikken av applikasjonen (koden)
• Unit testing scenarier type tester f. eks. UI test (test kode/skripter og resultater)
• Sluttbrukere hos Nøsted
• Hvordan applikasjonen brukes (bruksanvisning)
• Utviklere i din gruppe
• Endringer i koden (hva er det som ble endret, av hvem og når)
Hvorfor dokumenterer du?
• Andre utviklere hos en klient som Nøsted
• Applikasjonens oppsett (arkitektur)
• For at klientens utviklere vet hva slags teknologier de må ha på plass for å sette opp
applikasjonen
• Hvordan applikasjonen kjøres (kjøring på Docker, kobling mot database, osv)
• For at klientens utviklere får kjøre applikasjonen på en riktig måte
• Komponenter av applikasjonen (MVC, repo, klasser, osv)
• For at klientens utviklere vet om komponentene som applikasjonen er oppbygget av, hva det
gjør og hvorfor de er bygget slik
• Funksjonaliteter i applikasjonen (det som applikasjonen gjør)
• For at klientens utviklere vet hvilke krav spesifikasjoner ble utviklet som funksjonaliteter i
applikasjonen, sånn at de vet hva bør utvikles videre
• Logikken av applikasjonen (koden)
• For at klientens utviklere vet hva den særlige koden gjør, sånn at det blir lettere for dem å
endre koden når de legger til mer logikk eller funskonaliteter (velikeholde koden)
• Unit testing scenarier type tester f. eks. UI test (test kode/skripter og resultater)
• For at klientens utviklere vet hva den test koden/skript gjør, sånn at det blir lettere for dem å
kjøre same test etter at de er ferdige med applikasjonens oppsett eller de kan endre test
koden/skriptet etter videre utvikling av applikasjonen
Hvorfor dokumenterer du?
• Sluttbrukere hos Nøsted
• Hvordan applikasjonen brukes (bruksanvisning)
• For at klientens ansatte i ulike roller forstår hvordan de kan bruke applikasjonen
• Utviklere i din gruppe
• Endringer i koden (hva er det som ble endret, av hvem og når)
• For at dine gruppemedlemmer får se endringers log og notere noen utviklingsoppgaver
som “ferdige”.Hvorfor dokumenterer du?
• Sluttbrukere hos Nøsted
• Hvordan applikasjonen brukes (bruksanvisning)
• For at klientens ansatte i ulike roller forstår hvordan de kan bruke applikasjonen
• Utviklere i din gruppe
• Endringer i koden (hva er det som ble endret, av hvem og når)
• For at dine gruppemedlemmer får se endringers log og notere noen utviklingsoppgaver
som “ferdige”.
Hvordan dokumenterer du?
• Github!
• Gjennom Github README
• Applikasjonens oppsett (arkitektur)
• Hvordan applikasjonen kjøres (kjøring på Docker, kobling mot database, osv)
• Komponenter av applikasjonen (MVC, repo, klasser, osv)
• Funksjonaliteter i applikasjonen (det som applikasjonen gjør)
• Gjennom Github Wiki
• Unit testing scenarier type tester f. eks. UI test (test kode/skripter og resultater)
• Hvordan applikasjonen brukes (brukesanvisning)
• Gjennom Github Actions
• Endringer i koden (hva er det som ble endret, av hvem og når)
Github Wiki: https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis
Hvordan dokumenterer du?
• I selvekodens fil
• Gjennom «kommentarer»
• Logikken av applikasjonen (Hva den særlige koden gjør)
Kvalitetssikring av dokumentasjon
• Må testes med familie medlemmer, venner og klientens ansatte (både utviklere
og sluttbrukere) for å sikre at dokumentasjonen er lett å forstå
• Må oppdateres hver gang du forbedrer koden eller legger til en ny komponent
eller funksjonalitet
